redis:
  sentinel:
    master: ${REDIS_MASTER:mymaster}
    nodes: ${REDIS_SENTINEL_NODES:redis-headless.redis.svc.cluster.local:26379}
  password: ${REDIS_PASSWORD:abcd}

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis
        liveness:
          include: ping
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      password: ${REDIS_PASSWORD:abcd}
      sentinel:
        master: ${REDIS_MASTER:mymaster}
        nodes: ${REDIS_SENTINEL_NODES:redis-headless.redis.svc.cluster.local:26379}
        password: ${REDIS_PASSWORD:abcd}

logging:
  level:
    org.springframework.boot.actuate.health: DEBUG
    com.example.redisk8sdemo.health: DEBUG