apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-application.fullname" . }}-properties
  {{- include "configmap-properties.labels" . | nindent 2 }}
  data:
    {{- with .Values.configmapProperties.fileName }}
    {{- include "configmap-properties.filedata" (dict "ConfigMapName" . "Root" $) }}
    {{- end }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-application.fullname" . }}-configfiles
  {{- include "common-application.labels" . | nindent 2 }}
data: {{ (.Files.Glob "files/configfiles/*").AsConfig | nindent 2 }}
