apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-k8s-demo
  template:
    metadata:
      labels:
        app: redis-k8s-demo
    spec:
      containers:
        - name: redis-k8s-demo
          image: k8s-demo:test_07
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_MASTER
              value: "mymaster"
            - name: REDIS_SENTINEL_NODES
              value: "redis-headless.redis.svc.cluster.local:26379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          # Resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Startup probe with more lenient settings
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 20
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          # Readiness probe
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3